http:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "postgres"
  postgres:
    host: "dpg-damn9u3m8hqs739ch2lg-a"
    port: 5432
    user: "postgre_wvqg_user"
    password: "xCAJ0Eu2HaDn77VHabwNEEFEKWVe0WRi"
    database: "postgre_wvqg"
